server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /health {
        access_log off;
        default_type application/json;
        return 200 '{"status":"ok","service":"pickora"}';
    }

    location /data/ {
        alias /usr/share/nginx/data/;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Cache-Control "public, max-age=900" always;

        autoindex off;
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
